#pragma config(Motor,  port2,           lfWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lbWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rfWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rbWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           l1Motor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           l2Motor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           l3Motor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           l4Motor,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rkCompetition.h"

void init() { }
task auton() { }
task userOp() {

	while(true) {

		motor[lfWheel] = vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
		motor[rfWheel] = -(vexRT[Ch3] - vexRT[Ch4] - vexRT[Ch1]);
		motor[lbWheel] = vexRT[Ch3] + vexRT[Ch4] - vexRT[Ch1];
		motor[rbWheel] = -(vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch1]);

		if(vexRT[Btn5U] == 1 || vexRT[Btn6U] == 1) {
			motor[l1Motor] = 127;
			motor[l2Motor] = 127;
			motor[l3Motor] = 127;
			motor[l4Motor] = 127;
		}
		else if(vexRT[Btn5D] == 1 || vexRT[Btn6D] == 1) {
			motor[l1Motor] = -127;
			motor[l2Motor] = -127;
			motor[l3Motor] = -127;
			motor[l4Motor] = -127;
		}
		else {
			motor[l1Motor] = 0;
			motor[l2Motor] = 0;
			motor[l3Motor] = 0;
			motor[l4Motor] = 0;
		}
}

}
void endAuton() { }
void endUserOp() { }
